// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BlogItem: typeof import('./src/components/BlogItem.vue')['default']
    BlogList: typeof import('./src/components/BlogList.vue')['default']
    BlogPost: typeof import('./src/components/BlogPost.vue')['default']
    'Carbon:binoculars': typeof import('virtual:vite-icons/carbon/binoculars')['default']
    'Carbon:bullhorn': typeof import('virtual:vite-icons/carbon/bullhorn')['default']
    'Carbon:close': typeof import('virtual:vite-icons/carbon/close')['default']
    'Carbon:connectionTwoWay': typeof import('virtual:vite-icons/carbon/connection-two-way')['default']
    'Carbon:earth': typeof import('virtual:vite-icons/carbon/earth')['default']
    'Carbon:education': typeof import('virtual:vite-icons/carbon/education')['default']
    'Carbon:logoGithub': typeof import('virtual:vite-icons/carbon/logo-github')['default']
    'Carbon:logoLinkedin': typeof import('virtual:vite-icons/carbon/logo-linkedin')['default']
    'Carbon:logoSlack': typeof import('virtual:vite-icons/carbon/logo-slack')['default']
    'Carbon:logoTwitter': typeof import('virtual:vite-icons/carbon/logo-twitter')['default']
    'Carbon:moon': typeof import('virtual:vite-icons/carbon/moon')['default']
    'Carbon:shareKnowledge': typeof import('virtual:vite-icons/carbon/share-knowledge')['default']
    'Carbon:sun': typeof import('virtual:vite-icons/carbon/sun')['default']
    'Carbon:userAvatarFilledAlt': typeof import('virtual:vite-icons/carbon/user-avatar-filled-alt')['default']
    'Carbon:userMultiple': typeof import('virtual:vite-icons/carbon/user-multiple')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    CourseSummary: typeof import('./src/components/CourseSummary.vue')['default']
    DarkThemeToggle: typeof import('./src/components/DarkThemeToggle.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    LinkIconButton: typeof import('./src/components/LinkIconButton.vue')['default']
    LocaleToggle: typeof import('./src/components/LocaleToggle.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    LogoMark: typeof import('./src/components/LogoMark.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    SocialMediaButtons: typeof import('./src/components/SocialMediaButtons.vue')['default']
    'Twemoji:flagForFlagSpain': typeof import('virtual:vite-icons/twemoji/flag-for-flag-spain')['default']
    'Twemoji:flagForFlagUnitedKingdom': typeof import('virtual:vite-icons/twemoji/flag-for-flag-united-kingdom')['default']
  }
}

export { }
