// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BlogItem: typeof import('./src/components/BlogItem.vue')['default']
    BlogList: typeof import('./src/components/BlogList.vue')['default']
    BlogPost: typeof import('./src/components/BlogPost.vue')['default']
    'Carbon:moon': typeof import('virtual:vite-icons/carbon/moon')['default']
    'Carbon:sun': typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonLogoLinkedin: typeof import('virtual:vite-icons/carbon/logo-linkedin')['default']
    CarbonLogoSlack: typeof import('virtual:vite-icons/carbon/logo-slack')['default']
    CarbonLogoTwitter: typeof import('virtual:vite-icons/carbon/logo-twitter')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    DarkThemeToggle: typeof import('./src/components/DarkThemeToggle.vue')['default']
    'Fluent:documentBulletList24Regular': typeof import('virtual:vite-icons/fluent/document-bullet-list24-regular')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    LinkIconButton: typeof import('./src/components/LinkIconButton.vue')['default']
    LocaleToggle: typeof import('./src/components/LocaleToggle.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    LogoMark: typeof import('./src/components/LogoMark.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    SocialMediaButtons: typeof import('./src/components/SocialMediaButtons.vue')['default']
    'Twemoji:flagForFlagSpain': typeof import('virtual:vite-icons/twemoji/flag-for-flag-spain')['default']
    'Twemoji:flagForFlagUnitedKingdom': typeof import('virtual:vite-icons/twemoji/flag-for-flag-united-kingdom')['default']
  }
}

export { }
